server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: docker
    url: jdbc:postgresql://localhost:5432/hexgraph_dev
    username: docker
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
  profiles:
    active: dev
